#########
### Script: Mauve_run.pbs
#########
#PBS -N 07Nov2019Mauve.fasta
#PBS -q normal
#PBS -o /shares/common/users/i.warner/
#PBS -A i.warner
#PBS -S /bin/bash
#PBS -r n 
#PBS -l select=2:ncpus=4:mem=250GB
#PBS -l walltime=100:00:00

cd /home/i.warner/bin/mauve_snapshot_2015-02-13/linux-x64/

mauveAligner --output=/shares/common/users/i.warner/mauve_output/07Nov19Mauve.mauve /shares/common/users/i.warner/FASTA_sequences/All_Plus_Outgroup.fasta 