#########
### Script: Parsnp_run.pbs 
#########
#PBS -N 19Sept2019_parsnp.fasta
#PBS -q normal
#PBS -A i.warner
#PBS -S /bin/bash
#PBS -r n 
#PBS -l select=2:ncpus=4:mem=250GB
#PBS -l walltime=100:00:00

cd /home/i.warner/bin/Parsnp-Linux64-v1.2/

./parsnp -g /shares/common/users/i.warner/ref_genomes/BW25113-CP009273.1.gb -d /shares/common/users/i.warner/FASTA_sequences/ -p 2 -o /shares/common/users/i.warner/FASTA_sequences/alignments