#########
### Script: clustalo_run.pbs
#########
#PBS -N 21Aug2019_clustalo_align_phylip.phylip
#PBS -q normal
#PBS -A i.warner
#PBS -S /bin/bash
#PBS -r n 
#PBS -l select=1:ncpus=1:mem=35GB
#PBS -l walltime=12:00:00

cd /home/i.warner/bin

clustalo -i /shares/common/users/i.warner/FASTA_sequences/Ecoli_genomes_all.fasta -o /shares/common/users/i.warner/output_clustalo/Ecoli_genomes_aligned_clustal.phylip --outfmt=phylip

