#########
### Script: clustalo_run.pbs
#########
#PBS -N 27Aug2019_clustalo_align.fasta
#PBS -q normal
#PBS -A i.warner
#PBS -S /bin/bash
#PBS -r n 
#PBS -l select=2:ncpus=4:mem=250GB
#PBS -l walltime=100:00:00

cd /home/i.warner/bin

clustalo -i /shares/common/users/i.warner/FASTA_sequences/Ecoli_genomes_all.fasta -o /shares/common/users/i.warner/output_clustalo/Ecoli_genomes_aligned_clustal.fasta --outfmt=fasta --force

--log=/home/i.warner/qsub_scripts/clustalo_log.txt


