#########
### Script: mafft_run.pbs 
#########
#PBS -N 08Aug19_mafft_alignment.fasta
#PBS -q normal
#PBS -A i.warner
#PBS -S /bin/bash
#PBS -r n 
#PBS -l select=1:ncpus=1:mem=35GB
#PBS -l walltime=12:00:00

cd /home/i.warner/bin

mafft --globalpair --maxiterate 1000 /shares/common/users/i.warner/FASTA_sequences/Ecoli_genomes_all.fasta > /shares/common/users/i.warner/output_mafft/Ecoli_genomes_aligned.fasta  